// Generated by https://quicktype.io

export interface SubmitLayoutResponse {
  layout?: string | null;
  mail?:   MailVo;
}

export interface MailVo {
  body:     string;
  subject:  string;
  to_users: ToUserVo[];
}

export interface ToUserVo {
  user_account: string;
  user_email:   string;
  user_id:      string;
  user_name:    string;
}
